name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ vars.PROJECT_ID }}
  GAR_LOCATION: ${{ vars.GAR_LOCATION }}
  REPOSITORY: ${{ vars.REPOSITORY }}
  SERVICE: ${{ vars.SERVICE }}
  REGION: ${{ vars.REGION }}

jobs:
  build-and-deploy:

    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    # https://cloud.google.com/blog/products/identity-security/secure-your-use-of-third-party-tools-with-identity-federation
    - uses: 'google-github-actions/auth@v3'
      id: auth
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL}}
      # Outputs: project_id, credentials_file_path, auth_token, access_token

    # https://cloud.google.com/blog/products/devops-sre/deploy-to-cloud-run-with-github-actions/
    - name: Docker Auth
      id: docker-auth
      uses: 'docker/login-action@v3'
      with:
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'
        registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

    - name: Build and Push Container
      id: build-and-push
      run: |-
        IMAGE="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
        docker build -t "${IMAGE}" -f "apps/voice-api/Dockerfile" ./
        docker push "${IMAGE}"
        echo "image=${IMAGE}" >> $GITHUB_OUTPUT

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        service: ${{ env.SERVICE }}
        region: ${{ env.REGION }}
        image: ${{ steps.build-and-push.outputs.image }}

    - name: 'Show Output'
      id: show-output
      run: 'echo ${{ steps.deploy.outputs.url }}'